frontend/front/front/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from jobs import views as jobs_views
from devices import views as devices_views
from dashboards import views as dashboards_views
from mop import views as workflow_views
from reports import views as reports_views
from user import views as user_views
from notifications import views as notifications_views
from workflowReports import views as workflowReports_views
from complianceReports import views as complianceReports_views


urlpatterns = [
    url(r'^$', user_views.Login, name='login'),
    url(r'^logout$', user_views.Logout, name='logout'),
    url(r'^notifications$', notifications_views.Notification, name='Notification'),
    url(r'^triggers$', notifications_views.Trigger, name='Trigger'),
    url(r'^index$', devices_views.Index, name='Index'),
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('jobs.urls', namespace='jobs')),
    url(r'^devices/', include('devices.urls', namespace='devices')),
    url(r'^dashboards/', include('dashboards.urls', namespace='dashboards')),
    url(r'^workflow/', include('mop.urls', namespace='workflow')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^workflowReports/', include('workflowReports.urls', namespace='workflowReports')),
    url(r'^complianceReports/', include('complianceReports.urls', namespace='complianceReports')),


]

frontend/front/mop/urls.py
from django.conf.urls import url

from mop import views
 
urlpatterns =[
  url(r'^$', views.workflowList, name='workflowList'),
  url(r'^workflow-edit/$', views.workflowEdit, name='workflowViews'),
  url(r'^workflow-delete/$', views.workflowDelete, name='workflowViews'),

]

frontend/front/user/urls.py
from django.conf.urls import url

from user import views

urlpatterns =[
  url(r'^role/create$', views.RoleCreate, name='role_create'),
  url(r'^role/delete/(?P<obj_id>\w+)/$', views.RoleDelete, name='role_delete'),
  url(r'^role/edit/(?P<obj_id>\w+)/$', views.RoleEdit, name='role_edit'),
  url(r'^role$', views.Role, name='role'),

  url(r'^user_group/create$', views.UserGroupCreate, name='user_group_create'),
  url(r'^user_group/delete/(?P<obj_id>\w+)/$', views.UserGroupDelete, name='user_group_delete'),
  url(r'^user_group/edit/(?P<obj_id>\w+)/$', views.UserGroupEdit, name='user_group_edit'),
  url(r'^user_group$', views.UserGroup, name='user_group'),

  url(r'^create$', views.UserCreate, name='user_create'),
  url(r'^delete/(?P<obj_id>\w+)/$', views.UserDelete, name='user_delete'),
  url(r'^edit/(?P<obj_id>\w+)/$', views.UserEdit, name='user_edit'),
  url(r'^$', views.User, name='user'),

]

frontend/front/user/models.py
from django.db import models

# Create your models here.

frontend/front/user/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
import requests
import json
from front.common import authetication_required
from front.configuration import *
from requests.auth import HTTPBasicAuth


@authetication_required()
def UserCreate(request):
  message = ''
  url = API_URI + '/user'
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}
  url_all_user_groups = API_URI + '/user_groups'
  r = requests.get(url_all_user_groups, headers=headers)
  all_user_groups = {}
  if r.status_code == 200:
    all_user_groups = r.json()

  if request.method == 'POST':
    data = request.POST
    if data['password'] == data['confirm_password']:
      r = requests.post(url, data=json.dumps(data), headers=headers)
      if r.status_code == 200:
        return redirect(reverse("user:user"))
      else:
        if 'error' in r.text:
          message = r.json()['error']
        else:
          message = "Unknown error"
        # return render(request, 'user/user_form.html', {'message': message, 'action': 'add'})
    else : message = 'confirm password'
  return render(request, 'user/user_form.html',
                {'action': 'add',
                 'message': message,
                 "all_user_groups": all_user_groups})

@authetication_required()
def User(request):
  url = API_URI + '/user'
  headers = {'Authorization' : 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.get(url, headers=headers)
  if r.status_code == 200: jsondata = r.json()
  else: jsondata = {}
  return render(request, 'user/user.html', {'jsondata': jsondata})


@authetication_required()
def UserDelete(request, obj_id=None):
  url = API_URI + '/user/%s' % obj_id
  headers = {'Authorization': 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.delete(url, headers=headers)
  return redirect(reverse("user:user"))


@authetication_required()
def UserEdit(request, obj_id=None):
  message = ''
  url = API_URI + '/user/%s' % obj_id
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}

  url_all_user_groups = API_URI + '/user_groups'
  r = requests.get(url_all_user_groups, headers=headers)
  all_user_groups = {}
  if r.status_code == 200:
    all_user_groups = r.json()

  if request.method == 'POST':
    data = request.POST
    r1 = requests.put(url, data=json.dumps(data), headers=headers)
    if r1.status_code == 200:
      return redirect(reverse("user:user"))
    else:
      if 'error' in r1.text:
        message = r1.json()['error']
      else:
        message = "Unknown error"

  r = requests.get(url, headers=headers)
  jsondata = {}
  if r.status_code == 200:
    jsondata = r.json()

  return render(request, 'user/user_form.html',
                {'action': 'edit',
                 "obj": jsondata,
                 'message': message,
                 "all_user_groups": all_user_groups,
                 'message': message})


@authetication_required()
def UserGroupCreate(request):
  message = ''

  url = API_URI + '/user_group'
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}

  url_all_roles = API_URI + '/roles'
  r = requests.get(url_all_roles, headers=headers)
  all_roles = {}
  if r.status_code == 200:
    all_roles = r.json()
  if request.method == 'POST':
    all_roles_id = [role['id'] for role in all_roles["roles"]]
    data = request.POST
    user_group = {}
    if "name" in data:
      user_group["name"] = data["name"]

    user_group["roles"] = []
    for ugr in all_roles_id:
      ugr = str(ugr)
      #if ugr in data.keys():
      #if data[ugr] == "1":
      if ugr in data["selected_values"].split(','):
        #user_group["roles"].append({"id": ugr})
        user_group["roles"].append({"id": ugr})

    r1 = requests.post(url, data=json.dumps(user_group), headers=headers)

    if r1.status_code == 201:
      return redirect(reverse("user:user_group"))
    else:
      if 'error' in r1.text:
        message = r1.json()['error']
      else:
        message = "Unknown error"
      # return render(request, 'user_group/user_group_form.html', {'message': message, 'action': 'add'})

  return render(request, 'user_group/user_group_form.html',
                {'action': 'add',
                 'message': message,
                 "all_roles": all_roles})


@authetication_required()
def UserGroup(request):
  url = API_URI + '/user_groups'
  headers = {'Authorization' : 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.get(url, headers=headers)
  if r.status_code == 200: jsondata = r.json()
  else: jsondata = {}

  result = {'user_groups': []}
  if 'user_groups' in jsondata.keys():
    for user_group in jsondata['user_groups']:
      url_roles = API_URI + '/user_group/%s/roles' % user_group['id']
      r = requests.get(url_roles, headers=headers)
      roles = {}
      if r.status_code == 200:
        roles = r.json()

      if 'roles' in roles.keys():
        user_group['roles'] = roles['roles']

      result['user_groups'].append(user_group)

  return render(request, 'user_group/user_group.html', {'jsondata': result})


@authetication_required()
def UserGroupDelete(request, obj_id=None):
  url = API_URI + '/user_group/%s' % obj_id
  headers = {'Authorization': 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.delete(url, headers=headers)
  return redirect(reverse("user:user_group"))


@authetication_required()
def UserGroupEdit(request, obj_id=None):
  message = ''
  url = API_URI + '/user_group/%s' % obj_id
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}

  url_all_roles = API_URI + '/roles'
  r = requests.get(url_all_roles, headers=headers)
  all_roles = {}
  if r.status_code == 200:
    all_roles = r.json()

  all_roles_id = [role['id'] for role in all_roles["roles"]]

  if request.method == 'POST':
    data = request.POST
    user_group = {"roles": []}
    for ugr in all_roles_id:
      ugr = str(ugr)
      #if ugr in data.keys():
      #if data[ugr] == "1":
      if ugr in data["selected_values"].split(','):
        #user_group["roles"].append({"id": ugr})
        user_group["roles"].append({"id": ugr})

    r1 = requests.put(url, data=json.dumps(user_group), headers=headers)
    if r1.status_code == 201:
      return redirect(reverse("user:user_group"))
    else:
      if 'error' in r1.text:
        message = r1.json()['error']
      else:
        message = "Unknown error"

  r = requests.get(url, headers=headers)
  jsondata = {}
  if r.status_code == 200:
    jsondata = r.json()

  url_roles = API_URI + '/user_group/%s/roles' % obj_id
  r = requests.get(url_roles, headers=headers)
  roles = {}
  roles_id = {}
  if r.status_code == 200:
    roles = r.json()
    roles_id = [role['id'] for role in roles["roles"]]

  return render(request, 'user_group/user_group_form.html',
                {'action': 'edit',
                 "obj": jsondata,
                 "message": message,
                 "all_roles": all_roles,
                 "roles_id": roles_id})


@authetication_required()
def RoleCreate(request):
  message = ''

  url = API_URI + '/role'
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}

  url_all_permissions = API_URI + '/permissions'
  r = requests.get(url_all_permissions, headers=headers)
  all_permissions = {}
  if r.status_code == 200:
    all_permissions = r.json()

  if request.method == 'POST':
    data = request.POST
    role = {}
    if "name" in data:
      role["name"] = data["name"]

    all_permissions_id = [permission['id'] for permission in all_permissions["permissions"]]

    role["permissions"] = []
    for rp in all_permissions_id:
      rp = str(rp)
      # if rp in data.keys():
      if rp in data["selected_values"].split(','):
        #if data[rp] == "1":
        role["permissions"].append({"id": rp})

    r1 = requests.post(url, data=json.dumps(role), headers=headers)
    if r1.status_code == 201:
      return redirect(reverse("user:role"))
    else:
      if 'error' in r1.text:
        message = r1.json()['error']
      else:
        message = "Unknown error"

  return render(request, 'role/role_form.html',
                {'action': 'add',
                 'message': message,
                 "all_permissions": all_permissions})


@authetication_required()
def Role(request):
  url = API_URI + '/roles'
  headers = {'Authorization' : 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.get(url, headers=headers)
  if r.status_code == 200: jsondata = r.json()
  else: jsondata = {}

  result = {'roles': []}


  if 'roles' in jsondata.keys():
    for role in jsondata['roles']:
      url_permissions = API_URI + '/role/%s/permissions' % role['id']
      r = requests.get(url_permissions, headers=headers)
      permissions = {}
      if r.status_code == 200:
        permissions = r.json()

      role['permissions'] = permissions['permissions']

      result['roles'].append(role)

  return render(request, 'role/role.html', {'jsondata': result})


@authetication_required()
def RoleDelete(request, obj_id=None):
  url = API_URI + '/role/%s' % obj_id
  headers = {'Authorization': 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.delete(url, headers=headers)
  return redirect(reverse("user:role"))


@authetication_required()
def RoleEdit(request, obj_id=None):
  message = ''
  url = API_URI + '/role/%s' % obj_id
  headers = {'Authorization': 'JWT %s' % request.session['jwt_token']}

  url_all_permissions = API_URI + '/permissions'
  r = requests.get(url_all_permissions, headers=headers)
  all_permissions = {}
  if r.status_code == 200:
    all_permissions = r.json()

  all_permissions_id = [permission['id'] for permission in all_permissions["permissions"]]

  if request.method == 'POST':
    data = request.POST
    role = {"permissions": []}
    for rp in all_permissions_id:
      rp = str(rp)
      # if rp in data.keys():
      if rp in data["selected_values"].split(','):
        # if data[rp] == "1":

frontend/front/user/templates/role/role.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

.left-color {
    background-color: #f4f3f5;
}
.right-color {
    background-color: white;
}
</style>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/material-icons.css' %}">
    <link rel="stylesheet" href="{% static "assets/css/aos.css" %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Center.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jobs.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/jqx.base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/jqx.energyblue.css' %}">
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/readmore.min.js' %}"></script>

</head>

<body>
 <style>
.center {
    position: absolute;
    left: 0;
    top: 50%;
    width: 100%;
    text-align: center;
    font-size: 18px;
}
.topleft {
    top: 20%;
    left: 5%;
    font-size: 18px;
}
.topright {
    position: absolute;
    top: 8px;
    right: 16px;
	text-align: center;
    font-size: 18px;
}
input {
	border-radius: 10px;
}
.form-control {
	border-radius: 10px;
}



 
</style>

{% include "menu.html" %}

{% include "sidebar.html" with active="role" %}

    <div class="text-center">
    <div class="col col-xs-12">
        <div class="ministry-tabs">
            <div class="tab-content">

<div class="container" style="border-radius: 10px; width: 100%;">
    <div class="row" style="border-radius: 10px; margin-bottom: 10px;">
                  <div class="col text-right">
                    <div><a class="btn btn-primary" href="{% url 'user:role_create' %}" data-toggle="modal">New Role</a>
                  </div>
                </div>
              </div>
<div class="row" style="border-radius: 10px;">
    
        <div style="border-radius: 10px;">


                <div class="row" style="border-radius: 10px;">
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list display" id="roletable">
                  <thead>
                    <tr>
                        <th>Name</th>
                        <th>Permissions</th>
                        <th><em class="fa fa-cog"></em></th>
                    </tr> 
                  </thead>
                  <tbody>

                           {% for obj in jsondata.roles %}
                          <tr>
                            <td>{{ obj.name }}</td>
                              <td><div class="show-more">
                                  {% for perm in obj.permissions %}{{ perm.value }}<br>{% endfor %}
                              </div></td>
                            <td align="center">

          <form method="GET">
          <a class="btn btn-danger btn-s" role="button" href="#delete_{{ obj.id }}" data-toggle="modal" ><em class="fa fa-trash"></em></a>
          <a class="btn btn-default btn-s" role="button" href="{% url 'user:role_edit' obj_id=obj.id %}" data-toggle="modal"><em class="fa fa-pencil"></em></a>
          </form>

            <div class="modal fade" role="dialog" tabindex="-1" id="delete_{{ obj.id }}">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">X</span></button>
                        <h4 class="modal-title col col-xs-6 text-left">Delete Confirmation</h4></div>
                    <div class="modal-body">
                    <form method="post" action="{% url 'user:role_delete' obj_id=obj.id %}">{% csrf_token %}
                    <h4>Are you sure you want to delete : {{ obj.name }}</h4>
                    
                    <button class="btn btn-default" type="button" data-dismiss="modal" >NO</button>
                    <button type="submit" class="btn btn-danger">Yes</button>
                    </form>
              
                </div>
            </div>
        </div>
    </div>
    
    </td>
                          </tr>

                        {% endfor %}
                              
  </tbody>  
                    
                </table>
              </div>
         
            </div>

                </div>
            </div>
        </div>
    </div></div></div></div>
    {% if response.username %}
<script type="text/javascript">
$(window).load(function(){
	$("#create_notification").jqxNotification({
	    width: "auto",
	    position: "bottom-right",
	    opacity: 0.9,
	    autoOpen: false,
	    autoClose: true,
	    template: "success"
	});


	    $("#create_notification").jqxNotification("open");
	});
</script>

  <label id="create_notification" type="hidden">A user with name : {{response.username}}, was successfully created</label>

{% endif %}
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-animation.js' %}"></script>
    <script src="{% static "assets/js/aos.js" %}"></script>
    <script src="{% static 'assets/js/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/users.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/jqx-all.js' %}"></script>
</body>
 
    <script src="{% static 'assets/js/readmore.min.js' %}"></script>
     <style type="text/css">
         .show-more {
             max-height: 50px;
         }
     </style>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('.show-more').readmore({ speed: 75 });
        });
    </script>
</body>
{% include "footer.html" %}


</html>

frontend/front/user/templates/role/role_create.html
<head>
    <title>Create User</title>

{% include "header.html" %}
</head>
<body>
{% include "menu.html" %}  



<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

.left-color {
    background-color: #f4f3f5;
}
.right-color {
    background-color: white;
}
</style>




  
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-info">Create User</h2></div>
            <br />
            <h6 class="text-center" style="color: red">{{message}}</h6>
        <div class="col-md-6 col-md-offset-3 col-sm-6 col-xs-12 site-form">
            <form id="my-form" method="POST"> {% csrf_token %}
            <table>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Username</label></td>
                    <td class="right-color"><input class="right-color form-control" type="text" name="username" required="" ></td>
                    </tr>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Password</label></td>
                    <td class="right-color"><input class="right-color form-control" type="password" name="password" required="" ></td>
                    </tr>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Confirm Password</label></td>
                    <td class="right-color"><input class="right-color form-control" type="password" name="confirm_password" required="" ></td>
                    </tr>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Phone Number</label></td>
                    <td class="right-color"><input class="right-color form-control" type="tel" name="phone_number" required="" ></td>
                    </tr>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Email Address</label></td>
                    <td class="right-color"><input class="right-color form-control" type="text" name="email" required="" ></td>
                    </tr>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Group</label></td>
                    <td class="right-color"><select class="right-color form-control" name="group">
                        <option value="admin">Admin</option>
                        <option value="read_only">Read Only</option>
                        <option value="read_write">Read and Write </option>
                    </select></td>
                    </tr>
                </table> <br />
                <button class="btn btn-primary btn-lg text-right" type="submit" name="signup" value="true">SEND </button>
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
</body>


{% include "footer.html" %}

frontend/front/user/templates/role/role_form.html
{% load staticfiles %}
{% load users_tags %}

<head>
    <title>{% if obj %}Edit{% else %}Create{% endif %} Role</title>

{% include "header.html" %}
    <link rel="stylesheet" href="{% static 'assets/css/fSelect.css' %}">
    <script src="{% static 'assets/js/fSelect.js' %}"></script>
</head>
<body>

<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

.left-color {
    background-color: #f4f3f5;
}
.right-color {
    background-color: white;
}
</style>


{% include "menu.html" %}

{% include "sidebar.html" with active="role" %}

  <div class="text-center">
    <div class="col col-xs-10">

  
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center text-info">{% if obj %}Edit{% else %}Create{% endif %} Role</h2></div>
            <br />
            <h6 class="text-center" style="color: red">{{message}}</h6>
        <div class="col-md-6 col-md-offset-3 col-sm-6 col-xs-12 site-form">
            <form id="my-form" method="POST"> {% csrf_token %}
            <table>
                    <tr>
                    <td class="left-color"><label class="control-label col col-xs-6 text-left">Name</label></td>
                    <td class="right-color">
                        {% if action == 'add' %}
                            <input class="right-color form-control" type="text" name="name" required >
                        {% else %}
                            {{ obj.name }}
                        {% endif %}
                    </td>
                    </tr>
                    <tr>
                        <td class="left-color"><label class="control-label col col-xs-6 text-left">Permissions</label></td>
                        <td class="right-color">
                            {{ role }}

                            {% group_permission all_permissions.permissions as perms_by_object %}
                            <input type="hidden" id="selected_values" name="selected_values" value="{{ permissions_id|join:',' }}">
                            <select class="multiselectsearch" multiple="multiple">
                                {% for obj, perms in perms_by_object.items %}
                                <optgroup label="{{ obj }}">
                                    {% for perm in perms %}
                                    <option value="{{ perm.id }}" {% if perm.id in permissions_id %}selected {% endif %}>{{ perm.name }}</option>
                                    {% endfor %}
                                </optgroup>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                </table> <br />
                <button class="btn btn-primary btn-lg text-right" type="submit" name="signup" value="true">SEND </button>
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
    </div></div>
<script type="application/javascript">
    $('.multiselectsearch').fSelect();
</script>
</body>


{% include "footer.html" %}