frontend/front/front/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from jobs import views as jobs_views
from devices import views as devices_views
from dashboards import views as dashboards_views
from mop import views as workflow_views
from reports import views as reports_views
from user import views as user_views
from notifications import views as notifications_views
from workflowReports import views as workflowReports_views
from complianceReports import views as complianceReports_views


urlpatterns = [
    url(r'^$', user_views.Login, name='login'),
    url(r'^logout$', user_views.Logout, name='logout'),
    url(r'^notifications$', notifications_views.Notification, name='Notification'),
    url(r'^triggers$', notifications_views.Trigger, name='Trigger'),
    url(r'^index$', devices_views.Index, name='Index'),
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('jobs.urls', namespace='jobs')),
    url(r'^devices/', include('devices.urls', namespace='devices')),
    url(r'^dashboards/', include('dashboards.urls', namespace='dashboards')),
    url(r'^workflow/', include('mop.urls', namespace='workflow')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^workflowReports/', include('workflowReports.urls', namespace='workflowReports')),
    url(r'^complianceReports/', include('complianceReports.urls', namespace='complianceReports')),


]

frontend/front/mop/urls.py
from django.conf.urls import url

from mop import views
 
urlpatterns =[
  url(r'^$', views.workflowList, name='workflowList'),
  url(r'^workflow-edit/$', views.workflowEdit, name='workflowViews'),
  url(r'^workflow-delete/$', views.workflowDelete, name='workflowViews'),

]

frontend/front/reports/urls.py
from django.conf.urls import url

from reports import views

urlpatterns =[
  url(r'^$', views.JobReportList, name='ReportList'),
  url(r'^tasks/$', views.TaskReportList, name='TaskViews'),
  url(r'^export_result/(?P<job_id>\w+)/$', views.exportCSVResult, name='export_csv_result'),
]

frontend/front/reports/models.py
from django.db import models

# Create your models here.

frontend/front/reports/views.py

# Create your views here.

from django.shortcuts import render
import requests
from datetime import datetime
from front.common import authetication_required

from front.configuration import *
import json
import csv
from django.http.response import HttpResponse 
import unicodecsv

DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
KIBANA_PORT = '5601'


@authetication_required()
def JobReportList(request):
  url = API_URI + '/job'
  headers = {'Authorization' : 'JWT {0}'.format(request.session['jwt_token'])}
  r = requests.get(url, headers=headers)
  if r.status_code == 200: jsondata = r.json()
  else: jsondata = {}
  """for job in jsondata["jobs"]:
    if not job.get('compliance_execution_id') or not job.get('workflow_id'):
      jsondata["jobs"].remove(job)"""
  host = request.META.get('HTTP_HOST', 'localhost')
  hostname = host.split(':')[0]
  kibanaHost = 'http://' + hostname + ':' + KIBANA_PORT
  return render(request, 'reports/job_reports.html', {'jsondata': jsondata,
                                                      'kibana_host':kibanaHost,
                                                      'message': API_URI})


def get_tasks_info(jsonData, headers):
    for task in jsonData.get('tasks', []):
        r = requests.get(API_URI + '/device?id={}'.format(task['device_id']), headers=headers)
        if r.status_code != 200 or r.json()['devices'] == []:
            task['device_name'] = 'unknown({})'.format(task['device_id'])
        else:
            task['device_name'] = r.json()['devices'][0]['name']
        del task['device_id']
        if task['processing_start_time'] and task['processing_end_time']:
            startTime = datetime.strptime(task['processing_start_time'], DATE_FORMAT)
            endTime = datetime.strptime(task['processing_end_time'], DATE_FORMAT)
            task['duration'] = int((endTime - startTime).total_seconds())
        else:
            task['duration'] = -1
    return jsonData


@authetication_required()
def TaskReportList(request):
  jobId = request.GET.get('job_id')
  url = API_URI + '/task?job_id=' + jobId
  headers = {'Authorization' : 'JWT {0}'.format(request.session['jwt_token'])}
  task_result = requests.get(url, headers=headers)
  if task_result.status_code == 200: jsonData = task_result.json()
  else: jsonData = {}

  job_url = API_URI + '/job/' + jobId
  job_result = requests.get(job_url, headers=headers)
  if job_result.status_code == 200:
    job_jsonData = job_result.json()
  else:
    job_jsonData = {}

  jsonData = get_tasks_info(jsonData, headers)

  host = request.META.get('HTTP_HOST', 'localhost')
  hostname = host.split(':')[0]
  kibanaHost = 'http://' + hostname + ':' + KIBANA_PORT
  return render(request, 'reports/task_reports.html', {'tasks': jsonData,
                                                       'job_id': jobId,
                                                       'job': job_jsonData,
                                                       'kibana_host':kibanaHost,
                                                       'message': task_result.text})


@authetication_required()
def exportCSVResult(request, job_id):
  url = API_URI + '/task?job_id=' + job_id
  headers = {'Authorization': 'JWT {0}'.format(request.session['jwt_token'])}
  task_result = requests.get(url, headers=headers)
  if task_result.status_code == 200:
    jsonData = task_result.json()
  else:
    jsonData = {}

  jsonData = get_tasks_info(jsonData, headers)

  response = HttpResponse(content_type='text/csv')
  response['Content-Disposition'] = 'attachment; filename="job_%s.csv"' % job_id
  csv_writer = unicodecsv.writer(response, delimiter=';')
  csv_writer.writerow(['Device', 'Insertion Time', 'Processing Start Time', 'Duration (s)', 'Status', 'Result'])
  for task in jsonData.get('tasks', []):
    csv_writer.writerow([task['device_name'],
                         task['insertion_time'],
                         task['processing_start_time'],
                         task['duration'],
                         task['status'],
                         task['result']])

  return response


frontend/front/reports/templates/reports/job_reports.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jobs Reports</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/material-icons.css' %}">
    <link rel="stylesheet" href="{% static "assets/css/aos.css" %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Center.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/job-reports.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/toastr.min.css' %}">
    
    
</head>

<body>
{% include "menu.html" %}    

    <hr>
    <div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
             
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list display" id="jobreporttable" cellspacing="0" width="100%">
                  <thead>
                    <tr>
                    	<th hidden="true">Id</th>
                    	<th>Name</th>
                    	<th>Agent Type</th>
                        <th>Insertion Time</th>
                        <th>Scheduled</th>
                        <th>Schedule Date</th>
                        <th>status</th>
                        <th>processing start time</th>
                  	    <th>processing end time</th>
                        <th>Details</th>

		  </tr> 
                  </thead>
                  <tbody>
            

                           {% for obj in jsondata.jobs %}
                           <tr>
                            <td hidden="true">{{ obj.id }}</td>
                            <td><a href="tasks?job_id={{ obj.id }}">{{ obj.name }}</a></td>
                            <td>{{ obj.agent_type }}</td>
                            <td>{{ obj.insertion_time }}</td>
                            <td>{{ obj.is_scheduled }}</td>
                            <td>{{ obj.schedule_time }}</td>
                            <td><span title={{obj.status}} id="dot_status_{{obj.id}}" class="glyphicon dot-status-{{obj.status|lower}}"></span></td>
                            <td>{{ obj.processing_start_time }}</td>
                            <td>{{ obj.processing_end_time }}</td>
	                    <td><a target="_blank" href="{{kibana_host}}/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:297',display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:'optima-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'job_id:{{obj.id}}')),sort:!(_score,desc))"><button type="button" class="btn btn-sm btn-primary">view logs</button></a>


        </tr>

        {% endfor %}
                              
  </tbody>  
                    
                </table>
              </div>
            </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-animation.js' %}"></script>
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/jobs.js' %}"></script>
        <script src="{% static 'assets/js/toastr.min.js' %}"></script>
    
</body>
{% include "footer.html" %}
</html>

frontend/front/reports/templates/reports/task_reports.html


{% load staticfiles %}
{% load tasks_report_status_tags %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks Reports</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/material-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Center.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/MUSA_panel-table1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/task-reports.css' %}">
</head>

<body>
{% include "menu.html" %}    
    <hr>
    <div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">

    {% get_tasks_report_total_status tasks.tasks as tasks_status %}

    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            <div class="container" style="width: 100%;">
                <div class="row" style="width: 100%">
                    {% for status, total in tasks_status.items %}

                        <div class="col-xs-1">
                            <span title={{status}} class="glyphicon dot-status-{{status|lower}}">
                                <span>{{total}}</span>
                            </span>
                        </div>

                    {% endfor %}
                    <a style="float: right;" href="{% url 'reports:export_csv_result' job_id=job_id %}" target="_blank">
                        <button type="button" class="btn btn-sm btn-primary">Export CSV</button>
                    </a>
                </div>
            </div>

              <div class="panel-body">
                <table class="table table-striped table-bordered table-list display" id="taskreporttable" cellspacing="0" width="100%">
                  <thead>
                    <tr>
                    	<th hidden="true">Id</th>
                        <th>Device</th>
                        <th>Insertion Time</th>
                        <th>Processing Start Time</th>
                        <th>Duration (s)</th>
                        <th>Status</th>
                        <th>Details</th>
		    </tr> 
                  </thead>
                  <tbody>

                           {% for obj in tasks.tasks %}

                          <tr>
                            <td hidden="true">{{ obj.id }}</td>
                            <td {% if obj|display_result:job %}
                                rowspan="2"
                                {% endif %}>
                                {{ obj.device_name }}</td>
                            <td>{{ obj.insertion_time }}</td>
                            <td>{{ obj.processing_start_time}}</td>
                            <td id="duration_{{obj.id}}">{{ obj.duration}}</td>
                            <td><span title={{obj.status}} id="dot_status_{{obj.id}}" class="glyphicon dot-status-{{obj.status|lower}}"></span></td>
                            <td>
                                <a target="_blank" href="{{kibana_host}}/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:297',display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:'optima-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'task_id:{{obj.id}}')),sort:!(_score,desc))"><button type="button" class="btn btn-sm btn-primary">view logs</button></a>

                                {% if job.agent_type == 'configuration_differ_postcheck' and obj.result.configuration.diff %}

                                <button type="button" class="btn btn-sm btn-primary"  data-toggle="modal" data-target="#result_{{ obj.id }}">results</button>
                                <div class="modal fade" id="result_{{ obj.id }}" role="dialog">
                                    <div class="modal-dialog">

                                      <!-- Modal content-->
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                                          <h4 class="modal-title">Results</h4>
                                        </div>
                                        <div class="modal-body">
                                            <table class="table table-striped table-bordered table-list display" style="padding: 0; margin: 0;" cellspacing="0" width="100%">
                                            <tr>
                                                <td>Base</td>
                                                <td>Diff</td>
                                            </tr>
                                            <tr>
                                                <td><div class="show-more">
                                                    {% get_item obj.result.configuration 'pre-check' as precheck %}
                                                    {{ precheck|split_lines|safe }}
                                                </div></td>
                                                <td><div class="show-more">
                                                    {{ obj.result.configuration.diff|display_diff|safe }}
                                                </div></td>
                                            </tr>

                                                </table>
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                      </div>

                                    </div>
                                  </div>
                                {% endif %}
                            </td>
                        </tr>
                           {% if obj|display_result:job %}
                           <tr>
                               <td colspan="5" style="padding: 0; margin: 0;">
                                   <table class="table table-striped table-bordered table-list display" style="padding: 0; margin: 0;" cellspacing="0" width="100%">
                                       {% if job.agent_type == 'configuration_differ_postcheck' %}
                                       {% if obj.result.configuration.diff %}
                                       <tr>
                                           <th>Result diff</th>
                                           <td><div class="show-more">
                                               {{ obj.result.configuration.diff|display_diff|safe }}
                                           </div></td>
                                       </tr>
                                       {% endif %}
                                       {% elif job.agent_type == 'configuration_parser' %}
                                           {% for key, line in obj.result.configurations.items %}
                                           <tr>
                                               <th>{{ key }}</th>
                                               <td><div class="show-more">
                                                   {% if line.output %}
                                                        {{ line.output|split_lines|safe }}
                                                   {% endif %}
                                               </div></td>
                                           </tr>
                                           {% endfor %}
                                       {% else %}
                                            <tr>
                                               <th>Result</th>
                                               <td><div class="show-more">
                                                   {% if obj.result.configurations.output %}
                                                        {{ obj.result.configurations.output|split_lines|safe }}
                                                   {% else %}
                                                        {{ obj.result.configurations|split_lines|safe }}
                                                   {% endif %}
                                               </div></td>
                                           </tr>
                                       {% endif %}
                                   </table>
                               </td>
                           </tr>
                           {% endif %}
        {% endfor %}

                     </tbody>  
                    
                </table>
              </div>
            </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'assets/js/readmore.min.js' %}"></script>
     <style type="text/css">
         .show-more {
             max-height: 100px;
         }
     </style>
    <script type="text/javascript">
            $('.show-more').readmore({ speed: 75 });
    </script>
  <script>
  function refresh(){
  $.getJSON("http://"+window.location.host.split(':')[0]+ ":5000/task?job_id={{job_id}}",
		   function(data) {
	  var arrayLength = data['tasks'].length;
	  var array = data['tasks'];
	  var status = {'failed': 0, 'new': 0, 'ongoing': 0, 'queued': 0, 'successful': 0};
	  for (var i = 0; i < arrayLength; i++)
      {
		  var start_time = Date.parse(data['tasks'][i].processing_start_time);
		  var end_time = Date.parse(data['tasks'][i].processing_end_time);
		  if (end_time == null || start_time == null)
		  {
			  var duration = -1;
		  }
		  var duration = (end_time - start_time)/1000;
		  //console.log(duration);
		  $('#duration_' + data['tasks'][i].id).html(duration);
		  $("#dot_status_" + data['tasks'][i].id).attr('class', 'glyphicon dot-status-' + data['tasks'][i].status.toLowerCase());
		  $("#dot_status_" + data['tasks'][i].id).attr('title', data['tasks'][i].status);
		  //console.log("duration_" + data['tasks'][i].id);
		  //document.getElementById("duration_" + data['tasks'][i].id).value = duration;
		  //document.getElementById("dot_status_" + data['tasks'][i].id).className = "glyphicon dot-status-" + data['tasks'][i].status.toLowerCase();
		  //document.getElementById("dot_status_" + data['tasks'][i].id).title = data['tasks'][i].status;

          //status[data['tasks'][i].result.status.toLowerCase()]++;

	  }
	  for (var key in status) {
          $("span[title='" + key + "'] > span").html(status[key]);
      }
	  
		   });
  }
  
      window.setInterval(function(){
    	  refresh()
    	  },3000);
	 

  </script>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-animation.js' %}"></script>
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/js/toastr.min.js' %}"></script>
    <script src="{% static 'assets/js/jobs.js' %}"></script>


</body>
{% include "footer.html" %}
</html>